alias agfr='/home/ian/msc_project/docking/ADFRsuite/ADFRsuite_x86_64Linux_1.0/bin/agfr'
alias adfr='/home/ian/msc_project/docking/ADFRsuite/ADFRsuite_x86_64Linux_1.0/bin/adfr'
alias agfrgui='/home/ian/msc_project/docking/ADFRsuite/ADFRsuite_x86_64Linux_1.0/bin/agfrgui'
alias autosite='/home/ian/msc_project/docking/ADFRsuite/ADFRsuite_x86_64Linux_1.0/bin/autosite'
alias about='/home/ian/msc_project/docking/ADFRsuite/ADFRsuite_x86_64Linux_1.0/bin/about'
alias prepare_receptor='/home/ian/msc_project/docking/ADFRsuite/ADFRsuite_x86_64Linux_1.0/bin/prepare_receptor'
alias prepare_ligand='/home/ian/msc_project/docking/ADFRsuite/ADFRsuite_x86_64Linux_1.0/bin/prepare_ligand'
alias pythonsh='/home/ian/msc_project/docking/ADFRsuite/ADFRsuite_x86_64Linux_1.0/bin/pythonsh'
